### PR TITLE
Remove scenehandle write

### PR DESCRIPTION
**Pull request by romainf-unity**
The first commit is just a simple typo refactor, making the FullBodyIK code in sync with the coding style of the rest of the code.

The second commit is really what you want to review.

### CODE REVIEW

**Comment by mecanimdev** [comment]
look good to me

**Comment by romainf-unity** [comment]
Just added a new changeset adding the change into CHANGELOG.md: 7eecfe8

**Review by mecanimdev — APPROVED** [review]
look goot to me

**Review by oldio — APPROVED** [review]
👍

**Review by davidg-unity — APPROVED** [review]
Lgtm

**Pull request merged**
